name: linter


on:
  push:
    branches: 
    - master
    paths:
    - "**/*.go"
  pull_request:
    branches: 
    - master
    paths:
    - "**/*.go"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.16

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v2.5.0
        with:
          version: latest
          only-new-issues: true
          skip-go-installation: true
