name: linter


on:
  push:
    branches: 
    - master
    paths:
    - "**/*.go"
  pull_request:
    branches: 
    - master
    paths:
    - "**/*.go"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v2.4.0
        with:
          version: latest
          only-new-issues: true
          skip-go-installation: false
