-- MySQL Script generated by MySQL Workbench
-- Fri Feb 26 09:01:32 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS = @@UNIQUE_CHECKS, UNIQUE_CHECKS = 0;
SET @OLD_FOREIGN_KEY_CHECKS = @@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS = 0;
SET @OLD_SQL_MODE = @@SQL_MODE, SQL_MODE =
        'ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema blog
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema blog
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `blog` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;
USE `blog`;

-- -----------------------------------------------------
-- Table `blog`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blog`.`users`
(
    `id`              INT          NOT NULL AUTO_INCREMENT,
    `username`        VARCHAR(45)  NOT NULL,
    `hashed_password` VARCHAR(300) NOT NULL,
    `email`           VARCHAR(100) NOT NULL,
    `auth`            VARCHAR(45)  NOT NULL DEFAULT 'user',
    `role`            VARCHAR(45)  NOT NULL DEFAULT 'user',
    `avatar`          TEXT,
    PRIMARY KEY (`id`),
    UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE,
    UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE
)
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8mb4
    COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `blog`.`posts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blog`.`posts`
(
    `id`           INT          NOT NULL AUTO_INCREMENT,
    `title`        VARCHAR(100) NOT NULL,
    `content`      MEDIUMTEXT   NOT NULL,
    `author`       INT          NOT NULL,
    `last_updated` DATETIME     NULL DEFAULT NULL,
    PRIMARY KEY (`id`),
    INDEX `fk_posts_users_idx` (`author` ASC) VISIBLE,
    CONSTRAINT `fk_posts_users`
        FOREIGN KEY (`author`)
            REFERENCES `blog`.`users` (`id`)
)
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8mb4
    COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `blog`.`questions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blog`.`questions`
(
    `id`               INT          NOT NULL AUTO_INCREMENT,
    `question_content` MEDIUMTEXT   NOT NULL,
    `answer_content`   MEDIUMTEXT   NULL DEFAULT NULL,
    `email`            VARCHAR(100) NULL DEFAULT NULL,
    `create_time`      DATETIME     NULL DEFAULT NULL,
    `answer_time`      DATETIME     NULL DEFAULT NULL,
    `is_answered`      TINYINT      NULL DEFAULT NULL,
    PRIMARY KEY (`id`)
)
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8mb4
    COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `blog`.`replies`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blog`.`replies`
(
    `id`          INT         NOT NULL AUTO_INCREMENT,
    `content`     MEDIUMTEXT  NOT NULL,
    `email`       VARCHAR(45) NULL DEFAULT NULL,
    `posts_id`    INT         NOT NULL,
    `last_update` DATETIME    NULL DEFAULT NULL,
    PRIMARY KEY (`id`),
    INDEX `fk_replies_posts1_idx` (`posts_id` ASC) VISIBLE,
    CONSTRAINT `fk_replies_posts1`
        FOREIGN KEY (`posts_id`)
            REFERENCES `blog`.`posts` (`id`)
)
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8mb4
    COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE = @OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS = @OLD_UNIQUE_CHECKS;
